import { PrismaClient } from "@prisma/client";
import { deriveForeignConvenience } from "../src/lib/foreignConvenience.js";

const prisma = new PrismaClient();

type SeedPlace = {
  nameKo: string;
  nameEn?: string;
  category: "TOURIST" | "RESTAURANT" | "CAFE" | "LODGING";
  address: string;
  lat: number;
  lng: number;
  openTime: string;
  closeTime: string;
  closedDays?: string[];
  recommendedStayMin: number;
  priceTier: number;
  parkingAvailable?: boolean;
  reservationRequired?: boolean;
  localScore: number;
  tasteTags: string[];
  englishMenu?: boolean; // 명시 없으면 아래 deriveForeignConvenience()로 추정
  cardPayment?: boolean;
};

const PLACES: SeedPlace[] = [
  // ---- 관광지(TOURIST) ----
  {
    nameKo: "해운대해수욕장",
    nameEn: "Haeundae Beach",
    category: "TOURIST",
    address: "부산 해운대구 해운대해변로 264",
    lat: 35.1587,
    lng: 129.1604,
    openTime: "00:00",
    closeTime: "23:59",
    recommendedStayMin: 90,
    priceTier: 1,
    parkingAvailable: true,
    localScore: 0.7,
    tasteTags: ["nature", "photo", "landmark", "activity"],
  },
  {
    nameKo: "광안리해수욕장",
    nameEn: "Gwangalli Beach",
    category: "TOURIST",
    address: "부산 수영구 광안해변로 219",
    lat: 35.1531,
    lng: 129.1186,
    openTime: "00:00",
    closeTime: "23:59",
    recommendedStayMin: 90,
    priceTier: 1,
    parkingAvailable: true,
    localScore: 0.75,
    tasteTags: ["nature", "nightview", "photo", "landmark"],
  },
  {
    nameKo: "감천문화마을",
    nameEn: "Gamcheon Culture Village",
    category: "TOURIST",
    address: "부산 사하구 감내2로 203",
    lat: 35.0975,
    lng: 129.0107,
    openTime: "09:00",
    closeTime: "18:00",
    recommendedStayMin: 120,
    priceTier: 1,
    parkingAvailable: true,
    localScore: 0.68,
    tasteTags: ["culture", "photo", "landmark", "hidden_local"],
  },
  {
    nameKo: "태종대",
    nameEn: "Taejongdae",
    category: "TOURIST",
    address: "부산 영도구 전망로 24",
    lat: 35.0508,
    lng: 129.0872,
    openTime: "04:00",
    closeTime: "24:00",
    recommendedStayMin: 100,
    priceTier: 1,
    parkingAvailable: true,
    localScore: 0.66,
    tasteTags: ["nature", "activity", "photo", "landmark"],
  },
  {
    nameKo: "자갈치시장",
    nameEn: "Jagalchi Market",
    category: "TOURIST",
    address: "부산 중구 자갈치해안로 52",
    lat: 35.0968,
    lng: 129.0306,
    openTime: "05:00",
    closeTime: "22:00",
    recommendedStayMin: 60,
    priceTier: 2,
    localScore: 0.72,
    tasteTags: ["food", "culture", "hidden_local"],
  },
  {
    nameKo: "국제시장",
    nameEn: "Gukje Market",
    category: "TOURIST",
    address: "부산 중구 신창동4가",
    lat: 35.1001,
    lng: 129.0244,
    openTime: "09:00",
    closeTime: "20:00",
    recommendedStayMin: 60,
    priceTier: 2,
    localScore: 0.6,
    tasteTags: ["shopping", "culture", "food"],
  },
  {
    nameKo: "용두산공원",
    nameEn: "Yongdusan Park",
    category: "TOURIST",
    address: "부산 중구 용두산길 37-55",
    lat: 35.1005,
    lng: 129.0323,
    openTime: "00:00",
    closeTime: "23:59",
    recommendedStayMin: 60,
    priceTier: 1,
    localScore: 0.55,
    tasteTags: ["landmark", "photo", "nightview"],
  },
  {
    nameKo: "오륙도 스카이워크",
    nameEn: "Oryukdo Skywalk",
    category: "TOURIST",
    address: "부산 남구 오륙도로 137",
    lat: 35.1327,
    lng: 129.1194,
    openTime: "09:00",
    closeTime: "18:00",
    recommendedStayMin: 40,
    priceTier: 1,
    parkingAvailable: true,
    localScore: 0.58,
    tasteTags: ["nature", "photo", "hidden_local"],
  },
  {
    nameKo: "송정해수욕장",
    nameEn: "Songjeong Beach",
    category: "TOURIST",
    address: "부산 해운대구 송정해변로 62",
    lat: 35.1783,
    lng: 129.1997,
    openTime: "00:00",
    closeTime: "23:59",
    recommendedStayMin: 80,
    priceTier: 1,
    parkingAvailable: true,
    localScore: 0.8,
    tasteTags: ["nature", "activity", "hidden_local", "relax"],
  },
  {
    nameKo: "이기대 해안산책로",
    nameEn: "Igidae Coastal Walk",
    category: "TOURIST",
    address: "부산 남구 용호동",
    lat: 35.1339,
    lng: 129.1263,
    openTime: "00:00",
    closeTime: "23:59",
    recommendedStayMin: 90,
    priceTier: 1,
    localScore: 0.77,
    tasteTags: ["nature", "activity", "hidden_local", "relax"],
  },
  {
    nameKo: "흰여울문화마을",
    nameEn: "Huinnyeoul Culture Village",
    category: "TOURIST",
    address: "부산 영도구 영선동4가",
    lat: 35.0764,
    lng: 129.0483,
    openTime: "00:00",
    closeTime: "23:59",
    recommendedStayMin: 70,
    priceTier: 1,
    localScore: 0.82,
    tasteTags: ["photo", "hidden_local", "culture"],
  },
  {
    nameKo: "부산시립미술관",
    nameEn: "Busan Museum of Art",
    category: "TOURIST",
    address: "부산 해운대구 APEC로 58",
    lat: 35.1698,
    lng: 129.1364,
    openTime: "10:00",
    closeTime: "18:00",
    closedDays: ["MON"],
    recommendedStayMin: 90,
    priceTier: 1,
    parkingAvailable: true,
    localScore: 0.5,
    tasteTags: ["culture", "indoor", "history"],
  },
  {
    nameKo: "다대포해수욕장",
    nameEn: "Dadaepo Beach",
    category: "TOURIST",
    address: "부산 사하구 다대동",
    lat: 35.0489,
    lng: 128.965,
    openTime: "00:00",
    closeTime: "23:59",
    recommendedStayMin: 90,
    priceTier: 1,
    parkingAvailable: true,
    localScore: 0.73,
    tasteTags: ["nature", "nightview", "hidden_local", "relax"],
  },

  // ---- 식당(RESTAURANT) ----
  {
    nameKo: "삼진어묵 본점",
    nameEn: "Samjin Fish Cake Main Store",
    category: "RESTAURANT",
    address: "부산 영도구 태종로 99번길 36",
    lat: 35.0766,
    lng: 129.0468,
    openTime: "08:00",
    closeTime: "20:00",
    recommendedStayMin: 50,
    priceTier: 2,
    parkingAvailable: true,
    localScore: 0.65,
    tasteTags: ["food", "hidden_local"],
  },
  {
    nameKo: "할매집 돼지국밥",
    nameEn: "Halmaejip Pork Soup",
    category: "RESTAURANT",
    address: "부산 부산진구 서면로68번길",
    lat: 35.158,
    lng: 129.0594,
    openTime: "07:00",
    closeTime: "22:00",
    recommendedStayMin: 45,
    priceTier: 1,
    localScore: 0.88,
    tasteTags: ["food", "hidden_local"],
    englishMenu: false, // 현지인 단골집이라 영어 메뉴 없음
  },
  {
    nameKo: "자갈치 회센터",
    nameEn: "Jagalchi Sashimi Center",
    category: "RESTAURANT",
    address: "부산 중구 자갈치해안로 52",
    lat: 35.0965,
    lng: 129.0306,
    openTime: "10:00",
    closeTime: "21:00",
    recommendedStayMin: 60,
    priceTier: 3,
    reservationRequired: true,
    localScore: 0.6,
    tasteTags: ["food", "landmark"],
    englishMenu: true, // 관광객 상권, 영어 메뉴판 보유
    cardPayment: true,
  },
  {
    nameKo: "청사포 물회거리",
    nameEn: "Cheongsapo Sashimi Street",
    category: "RESTAURANT",
    address: "부산 해운대구 청사포로 41",
    lat: 35.1687,
    lng: 129.1849,
    openTime: "10:30",
    closeTime: "21:00",
    recommendedStayMin: 60,
    priceTier: 3,
    parkingAvailable: true,
    localScore: 0.79,
    tasteTags: ["food", "hidden_local", "nature"],
  },
  {
    nameKo: "전포동 곱창골목",
    nameEn: "Jeonpo-dong Gopchang Street",
    category: "RESTAURANT",
    address: "부산 부산진구 전포동",
    lat: 35.1533,
    lng: 129.0644,
    openTime: "16:00",
    closeTime: "24:00",
    recommendedStayMin: 70,
    priceTier: 2,
    localScore: 0.7,
    tasteTags: ["food", "hidden_local"],
  },
  {
    nameKo: "남포동 씨앗호떡",
    nameEn: "Nampo-dong Seed Hotteok",
    category: "RESTAURANT",
    address: "부산 중구 남포동2가",
    lat: 35.0968,
    lng: 129.03,
    openTime: "10:00",
    closeTime: "22:00",
    recommendedStayMin: 20,
    priceTier: 1,
    localScore: 0.63,
    tasteTags: ["food", "landmark"],
  },
  {
    nameKo: "해운대 암소갈비집",
    nameEn: "Haeundae Amso Galbi",
    category: "RESTAURANT",
    address: "부산 해운대구 구남로",
    lat: 35.1636,
    lng: 129.1603,
    openTime: "11:00",
    closeTime: "22:00",
    recommendedStayMin: 70,
    priceTier: 4,
    reservationRequired: true,
    parkingAvailable: true,
    localScore: 0.55,
    tasteTags: ["food"],
  },
  {
    nameKo: "서면 밀면골목",
    nameEn: "Seomyeon Milmyeon Alley",
    category: "RESTAURANT",
    address: "부산 부산진구 서면",
    lat: 35.1571,
    lng: 129.0587,
    openTime: "10:00",
    closeTime: "21:00",
    recommendedStayMin: 40,
    priceTier: 1,
    localScore: 0.74,
    tasteTags: ["food", "hidden_local"],
  },

  // ---- 카페(CAFE) ----
  {
    nameKo: "초량 이바구 카페",
    nameEn: "Choryang Ibagu Cafe",
    category: "CAFE",
    address: "부산 동구 초량동",
    lat: 35.115,
    lng: 129.0403,
    openTime: "10:00",
    closeTime: "21:00",
    recommendedStayMin: 50,
    priceTier: 2,
    localScore: 0.6,
    tasteTags: ["cafe", "hidden_local", "photo"],
  },
  {
    nameKo: "전포카페거리 모모스커피",
    nameEn: "Jeonpo Momos Coffee",
    category: "CAFE",
    address: "부산 부산진구 전포대로199번길",
    lat: 35.158,
    lng: 129.062,
    openTime: "10:00",
    closeTime: "22:00",
    recommendedStayMin: 50,
    priceTier: 2,
    localScore: 0.83,
    tasteTags: ["cafe", "hidden_local", "photo"],
  },
  {
    nameKo: "흰여울카페",
    nameEn: "Huinnyeoul Cafe",
    category: "CAFE",
    address: "부산 영도구 영선동4가",
    lat: 35.077,
    lng: 129.049,
    openTime: "10:00",
    closeTime: "20:00",
    recommendedStayMin: 45,
    priceTier: 2,
    localScore: 0.78,
    tasteTags: ["cafe", "photo", "nature"],
  },
  {
    nameKo: "청사포 카페거리",
    nameEn: "Cheongsapo Cafe Street",
    category: "CAFE",
    address: "부산 해운대구 청사포로",
    lat: 35.17,
    lng: 129.185,
    openTime: "10:00",
    closeTime: "21:00",
    recommendedStayMin: 50,
    priceTier: 2,
    localScore: 0.71,
    tasteTags: ["cafe", "nature", "nightview"],
  },
  {
    nameKo: "해리단길 카페",
    nameEn: "Haeridan-gil Cafe",
    category: "CAFE",
    address: "부산 해운대구 해리단길",
    lat: 35.156,
    lng: 129.152,
    openTime: "11:00",
    closeTime: "22:00",
    recommendedStayMin: 45,
    priceTier: 2,
    localScore: 0.69,
    tasteTags: ["cafe", "photo", "hidden_local"],
  },
  {
    nameKo: "광안리 오션뷰 카페",
    nameEn: "Gwangalli Ocean View Cafe",
    category: "CAFE",
    address: "부산 수영구 광안해변로",
    lat: 35.1535,
    lng: 129.1183,
    openTime: "09:00",
    closeTime: "23:00",
    recommendedStayMin: 60,
    priceTier: 3,
    localScore: 0.72,
    tasteTags: ["cafe", "nightview", "photo"],
  },

  // ---- 숙소(LODGING) ----
  {
    nameKo: "파라다이스호텔부산",
    nameEn: "Paradise Hotel Busan",
    category: "LODGING",
    address: "부산 해운대구 해운대해변로 296",
    lat: 35.1587,
    lng: 129.16,
    openTime: "00:00",
    closeTime: "23:59",
    recommendedStayMin: 480,
    priceTier: 4,
    reservationRequired: true,
    parkingAvailable: true,
    localScore: 0.5,
    tasteTags: ["relax", "landmark"],
  },
  {
    nameKo: "아난티 코브",
    nameEn: "Ananti Cove",
    category: "LODGING",
    address: "부산 기장군 기장읍",
    lat: 35.19,
    lng: 129.22,
    openTime: "00:00",
    closeTime: "23:59",
    recommendedStayMin: 480,
    priceTier: 4,
    reservationRequired: true,
    parkingAvailable: true,
    localScore: 0.55,
    tasteTags: ["relax", "nature", "photo"],
  },
  {
    nameKo: "영도 게스트하우스",
    nameEn: "Yeongdo Guesthouse",
    category: "LODGING",
    address: "부산 영도구 태종로",
    lat: 35.08,
    lng: 129.05,
    openTime: "00:00",
    closeTime: "23:59",
    recommendedStayMin: 480,
    priceTier: 2,
    reservationRequired: true,
    localScore: 0.62,
    tasteTags: ["relax", "hidden_local"],
  },
  {
    nameKo: "서면 시티호텔",
    nameEn: "Seomyeon City Hotel",
    category: "LODGING",
    address: "부산 부산진구 서면",
    lat: 35.1575,
    lng: 129.06,
    openTime: "00:00",
    closeTime: "23:59",
    recommendedStayMin: 480,
    priceTier: 2,
    reservationRequired: true,
    parkingAvailable: true,
    localScore: 0.45,
    tasteTags: ["relax"],
  },
  {
    nameKo: "송정 오션뷰 펜션",
    nameEn: "Songjeong Ocean View Pension",
    category: "LODGING",
    address: "부산 해운대구 송정동",
    lat: 35.179,
    lng: 129.2,
    openTime: "00:00",
    closeTime: "23:59",
    recommendedStayMin: 480,
    priceTier: 3,
    reservationRequired: true,
    parkingAvailable: true,
    localScore: 0.6,
    tasteTags: ["relax", "nature"],
  },

  // ---- 추가 관광지/체험(대표관광지 비중 확보) ----
  {
    nameKo: "부산 아쿠아리움",
    nameEn: "Sea Life Busan Aquarium",
    category: "TOURIST",
    address: "부산 해운대구 해운대해변로 266",
    lat: 35.1583,
    lng: 129.1596,
    openTime: "10:00",
    closeTime: "19:00",
    recommendedStayMin: 100,
    priceTier: 3,
    localScore: 0.5,
    tasteTags: ["indoor", "kids", "landmark", "activity"],
  },
  {
    nameKo: "송도 해상케이블카",
    nameEn: "Songdo Sky Cable Car",
    category: "TOURIST",
    address: "부산 서구 송도해변로 171",
    lat: 35.0765,
    lng: 129.0165,
    openTime: "09:00",
    closeTime: "22:00",
    recommendedStayMin: 60,
    priceTier: 3,
    parkingAvailable: true,
    localScore: 0.61,
    tasteTags: ["activity", "photo", "landmark"],
  },
  {
    nameKo: "부산현대미술관",
    nameEn: "Museum of Contemporary Art Busan",
    category: "TOURIST",
    address: "부산 사하구 낙동남로 1191",
    lat: 35.1046,
    lng: 128.9683,
    openTime: "10:00",
    closeTime: "18:00",
    closedDays: ["MON"],
    recommendedStayMin: 90,
    priceTier: 1,
    parkingAvailable: true,
    localScore: 0.52,
    tasteTags: ["culture", "indoor", "hidden_local"],
  },
  {
    nameKo: "동백섬",
    nameEn: "Dongbaekseom Island",
    category: "TOURIST",
    address: "부산 해운대구 우동",
    lat: 35.1535,
    lng: 129.1543,
    openTime: "00:00",
    closeTime: "23:59",
    recommendedStayMin: 60,
    priceTier: 1,
    localScore: 0.69,
    tasteTags: ["nature", "photo", "relax"],
  },
];

async function main() {
  console.log(`Seeding ${PLACES.length} places...`);
  await prisma.itineraryItem.deleteMany();
  await prisma.itineraryDay.deleteMany();
  await prisma.itinerary.deleteMany();
  await prisma.tripPreference.deleteMany();
  await prisma.trip.deleteMany();
  await prisma.place.deleteMany();

  for (const p of PLACES) {
    const derived = deriveForeignConvenience(p);
    await prisma.place.create({
      data: {
        nameKo: p.nameKo,
        nameEn: p.nameEn,
        category: p.category,
        address: p.address,
        lat: p.lat,
        lng: p.lng,
        openTime: p.openTime,
        closeTime: p.closeTime,
        closedDays: JSON.stringify(p.closedDays ?? []),
        recommendedStayMin: p.recommendedStayMin,
        priceTier: p.priceTier,
        parkingAvailable: !!p.parkingAvailable,
        reservationRequired: !!p.reservationRequired,
        localScore: p.localScore,
        tasteTags: JSON.stringify(p.tasteTags),
        hasEnglishMenu: p.englishMenu ?? derived.englishMenu,
        foreignCardPayment: p.cardPayment ?? derived.cardPayment,
      },
    });
  }
  console.log("Seed complete.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
