ALTER TABLE "User" ADD COLUMN "locale" TEXT NOT NULL DEFAULT 'KO';
ALTER TABLE "User" ADD COLUMN "nationality" TEXT;
ALTER TABLE "User" ADD COLUMN "dietType" TEXT NOT NULL DEFAULT 'NONE';
ALTER TABLE "User" ADD COLUMN "allergies" TEXT NOT NULL DEFAULT '[]';
ALTER TABLE "User" ADD COLUMN "travelStyle" TEXT NOT NULL DEFAULT 'BALANCED';
ALTER TABLE "User" ADD COLUMN "defaultTransport" TEXT NOT NULL DEFAULT 'TRANSIT';
